# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voiceAssistant.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1126, 675)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(770, 520, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(True)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Desktop/Tsec SE/Game/Mini Project B/WhatsApp Image 2021-05-02 at 8.14.23 PM.jpeg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 1131, 681))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("background.gif"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(810, 540, 71, 41))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(920, 520, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(True)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Desktop/Tsec SE/Game/Mini Project B/WhatsApp Image 2021-05-02 at 8.14.23 PM.jpeg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(970, 540, 71, 41))
        self.label_5.setObjectName("label_5")
        self.pushButton1 = QtWidgets.QPushButton(Form)
        self.pushButton1.setGeometry(QtCore.QRect(800, 480, 93, 28))
        self.pushButton1.setFlat(True)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(Form)
        self.pushButton2.setGeometry(QtCore.QRect(960, 480, 93, 28))
        self.pushButton2.setAutoDefault(False)
        self.pushButton2.setFlat(True)
        self.pushButton2.setObjectName("pushButton2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 30, 431, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("titleLabel.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(80, 50, 351, 51))
        self.label_6.setObjectName("label_6")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(570, 40, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("color:white;\n"
"background:transparent;\n"
"border-radius:none;\n"
"font-size:20px;")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser.setMidLineWidth(0)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(830, 40, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("color:white;\n"
"background:transparent;\n"
"border-radius:none;\n"
"font-size:20px;")
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.background.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.pushButton1.raise_()
        self.pushButton2.raise_()
        self.label.raise_()
        self.label_6.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">RUN</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">EXIT</span></p></body></html>"))
        self.pushButton1.setText(_translate("Form", "."))
        self.pushButton2.setText(_translate("Form", "."))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic; color:#ffffff;\">VIRTUAL VOICE ASSISTANT</span></p></body></html>"))
# import rec_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
